name: iOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: macos-14
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'

      # - name: Install Dependencies
      #   run: |
      #     brew install cocoapods
      #     pod install

      - name: Build iOS App
        run: |
          xcodebuild clean build -scheme TestApp -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
